FROM python:3.12-slim
WORKDIR /code
COPY ./celery_app ./celery_app
COPY requirements.txt .
COPY settings.py .
COPY .env .
RUN pip install --no-cache-dir --upgrade -r requirements.txt
CMD ["celery", "-A", "celery_app.tasks", "worker", "--loglevel=info"]